"""empty message

Revision ID: 786f5efc048e
Revises: 7aed96ea650d
Create Date: 2019-09-07 16:36:06.303347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786f5efc048e'
down_revision = '7aed96ea650d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildinguserlink',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('building_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildinguserlink')
    # ### end Alembic commands ###
